name: Nightly Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 5 * * *" # run at 5 AM UTC

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install dependencies
        run:  |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build (native) desktop + WASM
        run: zig build install

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install dependencies
        run: brew install sdl2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build (native) desktop + WASM
        run: zig build install
  
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Download SDL2 (MinGW)
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://www.libsdl.org/release/SDL2-devel-2.0.14-mingw.tar.gz
          file-name: SDL2.tar.gz
          location: .

      - name: Extract SDL2
        uses: brunoborges/justextract@v1
        with:
          file: SDL2.tar.gz
    
      - name: Create SDK file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .build_config/sdl.json
          contents: |
            {
              "i386-windows-gnu": {
                "include": "SDL2-2.0.14/i686-w64-mingw32/include",
                "libs": "SDL2-2.0.14/i686-w64-mingw32/lib",
                "bin": "SDL2-2.0.14/i686-w64-mingw32/bin"
              },
              "x86_64-windows-gnu": {
                "include": "SDL2-2.0.14/x86_64-w64-mingw32/include",
                "libs": "SDL2-2.0.14/x86_64-w64-mingw32/lib",
                "bin": "SDL2-2.0.14/x86_64-w64-mingw32/bin"
              }
            }
          write-mode: overwrite

      - name: Build (native) desktop + WASM
        run: zig build install